#!/bin/bash

PROJECT_ROOT=$(git rev-parse --show-toplevel)
MONOREPO_ROOT=$PROJECT_ROOT/..
BUILD_DIR=$MONOREPO_ROOT/build
CONFIG_PATH=$PROJECT_ROOT/.clang-tidy
COMPILE_COMMANDS_PATH=$BUILD_DIR/wasm2native/compile_commands.json
CLANG_TIDY_PATH=$(which clang-tidy)
if [[ "$CLANG_TIDY_PATH" == "" ]]; then
  # FIXME: Hard coded Homebrew installation point on macOS Ventura
  CLANG_TIDY_PATH=/opt/homebrew/opt/llvm/bin/clang-tidy
fi

# Find all files in THIS_DIR which end in .ino, .cpp, etc., as specified
# in the regular expression just below
FILE_LIST="$(find "$PROJECT_ROOT" | grep -E ".*(\.cpp|\.c)$")"

echo -e "Files found to lint = \n\"\"\"\n$FILE_LIST\n\"\"\""

# Format each file.
# - NB: do NOT put quotes around `$FILE_LIST` below or else the `clang-tidy` command will 
#   mistakenly see the entire blob of newline-separated file names as a SINGLE file name instead 
#   of as a new-line separated list of *many* file names!
$CLANG_TIDY_PATH -p $COMPILE_COMMANDS_PATH \
  --config-file=$CONFIG_PATH \
  --use-color --quiet \
  $FILE_LIST
